#!/bin/bash
# a wrapper to use latex diff in git as a difftool

TMPDIR=$(mktemp -d /tmp/git-latexdiff.XXX)
latexdiff "$1" "$2" > $TMPDIR/diff.tex
pdflatex -interaction nonstopmode -output-directory $TMPDIR $TMPDIR/diff.tex
evince $TMPDIR/diff.pdf
trap $(rm -rf $TMPDIR) EXIT
